allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

// هذا الجزء يحل مشكلة compileSdkVersion و flutter extension لمكتبة wakelock_plus
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
